plugins {
    id('com.android.library')
}

android {
    namespace 'com.termux.x11.stub'
    buildToolsVersion rootProject.ext.toolsVersion
    compileSdk rootProject.ext.compileApi
    defaultConfig {
        minSdk rootProject.ext.minApi
        //noinspection ExpiredTargetSdkVersion
        targetSdk rootProject.ext.targetApi
    }
    buildFeatures {
        buildConfig false
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.toVersion(rootProject.ext.javaLanguageVersion)
        targetCompatibility JavaVersion.toVersion(rootProject.ext.javaLanguageVersion)
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.9.1'
}
