package com.vectras.vm.integration

import android.app.PendingIntent
import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.os.Build
import java.util.UUID

/** Bounded dispatcher from Vectras to the external Termux RAFCODE-Phi runtime. */
object VectrasTermuxBridge {

    const val EXECUTION_MODE = "run_command_service"

    private val allowedBinaries = setOf(
        "qemu-system-x86_64",
        "qemu-system-x86_64-rafaelia",
        "qemu-system-x86_64-rafacodephi",
        "qemu-system-aarch64",
        "qemu-system-aarch64-rafaelia",
        "qemu-system-i386",
        "qemu-system-arm",
    )

    enum class State {
        DISPATCHED,
        VM_NOT_REQUIRED,
        TERMUX_NOT_INSTALLED,
        PERMISSION_REQUIRED,
        INVALID_BINARY,
        INVALID_ARGUMENTS,
        INVALID_GUEST_CHALLENGE,
        SERVICE_UNAVAILABLE,
        REQUEST_PERSISTENCE_FAILED,
        ERROR,
    }

    data class DispatchResult(
        val state: State,
        val transactionId: String?,
        val binaryName: String?,
        val component: String?,
        val executionProven: Boolean = false,
        val claimAllowed: Boolean = false,
        val safeState: String = "vm-stopped-no-image-mutation",
        val reason: String? = null,
        val requestSha256: String? = null,
        val argumentCount: Int? = null,
        val guestBootNonce: String? = null,
    )

    fun dispatchQemu(
        context: Context,
        binaryName: String,
        arguments: List<String>,
        vmRequired: Boolean,
        background: Boolean = true,
    ): DispatchResult = dispatchInternal(
        context = context,
        binaryName = binaryName,
        arguments = arguments,
        vmRequired = vmRequired,
        background = background,
        guestBootNonce = null,
    )

    /**
     * Dispatch with an explicit guest challenge.
     *
     * The caller must transport [guestBootNonce] into the guest, normally in a
     * kernel command line token generated by [GuestBootEvidenceContract.kernelArgument].
     * This method never injects or rewrites architecture-specific QEMU options.
     */
    fun dispatchQemuWithGuestEvidence(
        context: Context,
        binaryName: String,
        arguments: List<String>,
        vmRequired: Boolean,
        guestBootNonce: String = GuestBootEvidenceContract.generateNonce(),
        background: Boolean = true,
    ): DispatchResult {
        if (!GuestBootEvidenceContract.validNonce(guestBootNonce)) {
            return DispatchResult(
                State.INVALID_GUEST_CHALLENGE,
                null,
                binaryName,
                null,
                reason = "guest_boot_nonce_invalid",
                guestBootNonce = guestBootNonce,
            )
        }
        if (!GuestBootEvidenceContract.containsNonceArgument(arguments, guestBootNonce)) {
            return DispatchResult(
                State.INVALID_GUEST_CHALLENGE,
                null,
                binaryName,
                null,
                reason = "guest_boot_nonce_not_present_in_arguments",
                guestBootNonce = guestBootNonce,
            )
        }
        return dispatchInternal(
            context = context,
            binaryName = binaryName,
            arguments = arguments,
            vmRequired = vmRequired,
            background = background,
            guestBootNonce = guestBootNonce,
        )
    }

    fun newGuestBootNonce(): String = GuestBootEvidenceContract.generateNonce()

    fun guestBootKernelArgument(nonce: String): String =
        GuestBootEvidenceContract.kernelArgument(nonce)

    private fun dispatchInternal(
        context: Context,
        binaryName: String,
        arguments: List<String>,
        vmRequired: Boolean,
        background: Boolean,
        guestBootNonce: String?,
    ): DispatchResult {
        if (!vmRequired) {
            return DispatchResult(
                State.VM_NOT_REQUIRED,
                null,
                binaryName,
                null,
                guestBootNonce = guestBootNonce,
            )
        }
        if (!background) {
            return DispatchResult(
                State.INVALID_ARGUMENTS,
                null,
                binaryName,
                null,
                reason = "app_shell_runner_required",
                guestBootNonce = guestBootNonce,
            )
        }
        if (binaryName !in allowedBinaries) {
            return DispatchResult(
                State.INVALID_BINARY,
                null,
                binaryName,
                null,
                guestBootNonce = guestBootNonce,
            )
        }

        val boundedArguments = VectrasTermuxIpcContract.boundedArguments(arguments)
            ?: return DispatchResult(
                State.INVALID_ARGUMENTS,
                null,
                binaryName,
                null,
                reason = "arguments_outside_ipc_v3_contract",
                guestBootNonce = guestBootNonce,
            )

        if (guestBootNonce != null &&
            !GuestBootEvidenceContract.containsNonceArgument(boundedArguments, guestBootNonce)
        ) {
            return DispatchResult(
                State.INVALID_GUEST_CHALLENGE,
                null,
                binaryName,
                null,
                reason = "bounded_arguments_lost_guest_boot_nonce",
                guestBootNonce = guestBootNonce,
            )
        }

        if (!CrossRepoIntegrationManager.isTermuxInstalled(context)) {
            return DispatchResult(
                State.TERMUX_NOT_INSTALLED,
                null,
                binaryName,
                null,
                guestBootNonce = guestBootNonce,
            )
        }
        if (!hasRunCommandPermission(context)) {
            return DispatchResult(
                State.PERMISSION_REQUIRED,
                null,
                binaryName,
                null,
                reason = VectrasTermuxIpcContract.RUN_COMMAND_PERMISSION,
                guestBootNonce = guestBootNonce,
            )
        }

        val transactionId = "tx-vectras-termux-${UUID.randomUUID()}"
        val requestSha256 = VectrasTermuxIpcContract.sha256(
            VectrasTermuxIpcContract.canonicalRequest(
                transactionId = transactionId,
                binaryName = binaryName,
                arguments = boundedArguments,
                guestBootNonce = guestBootNonce,
            ),
        )
        if (!VectrasTermuxReceiptStore.writePending(
                context = context,
                transactionId = transactionId,
                binaryName = binaryName,
                arguments = boundedArguments,
                requestSha256 = requestSha256,
                guestBootNonce = guestBootNonce,
            )
        ) {
            return DispatchResult(
                State.REQUEST_PERSISTENCE_FAILED,
                transactionId,
                binaryName,
                null,
                reason = "pending_request_not_persisted",
                requestSha256 = requestSha256,
                argumentCount = boundedArguments.size,
                guestBootNonce = guestBootNonce,
            )
        }

        val receiptIntent = Intent(context, VectrasTermuxResultReceiver::class.java).apply {
            action = VectrasTermuxResultReceiver.ACTION_EXECUTION_RESULT
            putExtra(VectrasTermuxResultReceiver.EXTRA_TRANSACTION_ID, transactionId)
            putExtra(VectrasTermuxResultReceiver.EXTRA_BINARY_NAME, binaryName)
            putExtra(VectrasTermuxResultReceiver.EXTRA_REQUEST_SHA256, requestSha256)
        }
        val pendingFlags = PendingIntent.FLAG_UPDATE_CURRENT or
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                PendingIntent.FLAG_MUTABLE
            } else {
                0
            }
        val resultPendingIntent = PendingIntent.getBroadcast(
            context,
            transactionId.hashCode(),
            receiptIntent,
            pendingFlags,
        )

        val intent = Intent().apply {
            component = ComponentName(
                VectrasTermuxIpcContract.TERMUX_PACKAGE,
                VectrasTermuxIpcContract.SERVICE_CLASS,
            )
            action = VectrasTermuxIpcContract.ACTION_RUN_COMMAND
            putExtra(
                VectrasTermuxIpcContract.EXTRA_COMMAND_PATH,
                VectrasTermuxIpcContract.commandPath(binaryName),
            )
            putExtra(
                VectrasTermuxIpcContract.EXTRA_ARGUMENTS,
                boundedArguments.toTypedArray(),
            )
            putExtra(
                VectrasTermuxIpcContract.EXTRA_WORKDIR,
                VectrasTermuxIpcContract.WORKDIR,
            )
            putExtra(
                VectrasTermuxIpcContract.EXTRA_RUNNER,
                VectrasTermuxIpcContract.RUNNER_APP_SHELL,
            )
            putExtra(
                VectrasTermuxIpcContract.EXTRA_PENDING_INTENT,
                resultPendingIntent,
            )
        }

        return try {
            val component = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                context.startForegroundService(intent)
            } else {
                context.startService(intent)
            }
            if (component == null) {
                DispatchResult(
                    State.SERVICE_UNAVAILABLE,
                    transactionId,
                    binaryName,
                    null,
                    reason = "service_component_null",
                    requestSha256 = requestSha256,
                    argumentCount = boundedArguments.size,
                    guestBootNonce = guestBootNonce,
                )
            } else {
                DispatchResult(
                    state = State.DISPATCHED,
                    transactionId = transactionId,
                    binaryName = binaryName,
                    component = component.flattenToShortString(),
                    executionProven = false,
                    claimAllowed = false,
                    reason = "dispatch_accepted_execution_receipt_pending",
                    requestSha256 = requestSha256,
                    argumentCount = boundedArguments.size,
                    guestBootNonce = guestBootNonce,
                )
            }
        } catch (exc: SecurityException) {
            DispatchResult(
                State.PERMISSION_REQUIRED,
                transactionId,
                binaryName,
                null,
                reason = exc.javaClass.simpleName,
                requestSha256 = requestSha256,
                argumentCount = boundedArguments.size,
                guestBootNonce = guestBootNonce,
            )
        } catch (exc: RuntimeException) {
            DispatchResult(
                State.ERROR,
                transactionId,
                binaryName,
                null,
                reason = exc.javaClass.simpleName,
                requestSha256 = requestSha256,
                argumentCount = boundedArguments.size,
                guestBootNonce = guestBootNonce,
            )
        }
    }

    fun allowedBinaryNames(): Set<String> = allowedBinaries.toSet()

    private fun hasRunCommandPermission(context: Context): Boolean {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) return true
        return context.checkSelfPermission(VectrasTermuxIpcContract.RUN_COMMAND_PERMISSION) ==
            PackageManager.PERMISSION_GRANTED
    }
}
