apply plugin: 'com.android.library'

android {
    namespace "com.termux.view"
    compileSdk rootProject.ext.compileApi
    buildToolsVersion rootProject.ext.toolsVersion

    defaultConfig {
        minSdk rootProject.ext.minApi
        //noinspection ExpiredTargetSdkVersion
        targetSdk rootProject.ext.targetApi
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.toVersion(rootProject.ext.javaLanguageVersion)
        targetCompatibility JavaVersion.toVersion(rootProject.ext.javaLanguageVersion)
    }
}

dependencies {
    implementation "androidx.annotation:annotation:1.9.1"
    api project(":terminal-emulator")
    testImplementation 'junit:junit:4.13.2'
}
